baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://tryhendri.github.io/" # the base hostname & protocol for your site
title: "Hendri"
header-tag: "My Journey"

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
